### PR TITLE
Workaround for generating bool uniforms in ESSL1

### LINKED ISSUE #2223: uniforms of type bool are transpiled as uint when targeting #version 100
As the title says. This results in an exception

```
Unsigned integers are not supported on legacy ESSL.
```

To reproduce:

```
#version 310 es

layout(binding = 0) uniform Foo {
  bool bar;
} foo;

void main() {}
```

Disabling the relevant checks in spirv_glsl.cpp showed that `bar` was indeed changed into a `uint`.

### PR DESCRIPTION
**Pull request by elizagamedev**
Fixes #2223.

### CODE REVIEW

File: spirv_glsl.cpp [hunk 1]
```diff
@@ -15051,7 +15051,11 @@ string CompilerGLSL::flags_to_qualifiers_glsl(const SPIRType &type, const Bitset
 	{
 		auto &execution = get_entry_point();
 
-		if (flags.get(DecorationRelaxedPrecision))
+		if (type.basetype == SPIRType::UInt && is_legacy()) {
+			// HACK: This is a bool. See comment in type_to_glsl().
+			qual += "lowp ";
+		}
+		else if (flags.get(DecorationRelaxedPrecision))
```
Comment (HansKristian-Work) [inline spirv_glsl.cpp:15058]:
```suggestion
		if (type.basetype == SPIRType::UInt && is_legacy())
		{
			// HACK: This is a bool. See comment in type_to_glsl().
			qual += "lowp ";
		}
		else if (flags.get(DecorationRelaxedPrecision))
```

File: spirv_glsl.cpp [hunk 2]
```diff
@@ -15051,7 +15051,12 @@ string CompilerGLSL::flags_to_qualifiers_glsl(const SPIRType &type, const Bitset
 	{
 		auto &execution = get_entry_point();
 
-		if (flags.get(DecorationRelaxedPrecision))
+		if (type.basetype == SPIRType::UInt && is_legacy())
```
Comment (HansKristian-Work) [inline spirv_glsl.cpp:15054]:
```suggestion
		if (type.basetype == SPIRType::UInt && is_legacy_es())
```
